// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZRUd2Zi6vMoJSnyXy8NUvzg7ghpxKSrE',
    appId: '1:337167254845:web:1ce393c56aca8a324eb154',
    messagingSenderId: '337167254845',
    projectId: 'com-kokonstya-invoker',
    authDomain: 'com-kokonstya-invoker.firebaseapp.com',
    storageBucket: 'com-kokonstya-invoker.appspot.com',
    measurementId: 'G-7C32E0QK83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBBRlUfnzCDJ1U9j6aSem8AqI3q8eD6XU',
    appId: ' 1:337167254845:android:35cf8d91e30c4d814eb154',
    messagingSenderId: '337167254845',
    projectId: 'com-kokonstya-invoker',
    storageBucket: 'com-kokonstya-invoker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_BC545hnAp1zoeon-V4qewpGUN_hDiZE',
    appId: '1:337167254845:ios:fc93b831c2d7d85b4eb154',
    messagingSenderId: '337167254845',
    projectId: 'com-kokonstya-invoker',
    storageBucket: 'com-kokonstya-invoker.appspot.com',
    iosClientId:
        '337167254845-3k0g1nm5mtb3r38bicpofk18k40v1i19.apps.googleusercontent.com',
    iosBundleId: 'com.kokonstya.invoker',
  );
}
